# yml 模板
server:
  port: 8080
# 分组任务配置
chatbot-api:
  launchList: group01,group02 # 启动几组，就配置几组
  group01:
    groupName: ChatGPT AI Robot V1
    groupId:  # 知识星球ID
    cookie:  # 知识星球个人cookie信息
    openAiKey:  # 自行申请 https://beta.openai.com/overview
    cronExpression: 0/30 * * * * ? # 执行的频次配置，参考：cron.qqe2.com
    silenced: false
  group02:
    groupName: ChatGPT AI Robot V2
    groupId:  # 知识星球ID
    cookie:  # 知识星球个人cookie信息
    openAiKey:  # 自行申请 https://beta.openai.com/overview
    cronExpression: 0/30 * * * * ? # 执行的频次配置，参考：cron.qqe2.com
    silenced: true

Cola:
  PROXY_HOST:  # 代理地址
  PROXY_PORT:  # 代理端口